[workspace]

members = ["cornflakes-codegen",
            "cornflakes-libos",
            "echo-server",
            "cornflakes-utils",
            "data-structure-query",
            "kv-store",
            "kv-store-ds"]
            #"data-shuffle"]

#[profile.release]
#lto = "fat"
#codegen-units = 1
#panic = "abort"
#opt-level = 3
#debug = false
#debug-assertions = false
#overflow-checks = false
#incremental = false
#rpath = false

