[workspace]

members = ["cornflakes-codegen",
            "cornflakes-libos",
            "echo-server",
            "cornflakes-utils",
            "data-structure-query",
            "kv-store",
            "kv-store-ds"]
            #"data-shuffle"]
