sudo env RUST_BACKTRACE=1 LD_LIBRARY_PATH=/h/deeptir/cornflakes/dpdk-datapath/3rdparty/dpdk/install/lib/x86_64-linux-gnu /h/deeptir/cornflakes/target/release/ycsb_dpdk --config_file /h/deeptir/config/config.yaml --server_ip 198.19.200.1 --our_ip 198.19.200.2 --mode client --push_buf_type singlebuf --queries ~/ycsb-workloads/4K_250K_15M/workloadc/workloadc-1-batched.access --trace ~/ycsb-workloads/4K_250K_15M/workloadc/workloadc-1-batched.load --debug_level info --client_id 0 --num_clients 1 --num_threads 16 --serialization cornflakes1c-dynamic --time 30 --rate 50000 --value_size UniformOverSizes-1024 --num_values 4 --num_keys 4
sudo env RUST_BACKTRACE=1 LD_LIBRARY_PATH=/h/deeptir/cornflakes/dpdk-datapath/3rdparty/dpdk/install/lib/x86_64-linux-gnu taskset -c 2 nice -n -19 /h/deeptir/cornflakes/target/release/ycsb_
--mode server --config_file /h/deeptir/config/config.yaml --server_ip 198.19.200.1 --debug_level info --trace ~/ycsb-workloads/4K_250K_15M/workloadc/workloadc-1-batched.load --value_size UniformOverSizes-1024 --num_values 4 --num_keys 4 --serialization cornflakes1c-dynamic --push_buf_type arenaorderedsga --copy_threshold 32 --inline_mode objectheader
sudo env RUST_BACKTRACE=1 LD_LIBRARY_PATH=/h/deeptir/cornflakes/dpdk-datapath/3rdparty/dpdk/install/lib/x86_64-linux-gnu taskset -c 2 nice -n -19  /h/deeptir/cornflakes/target/release/ds_echo_mlx5 --mode server --config_file /h/deeptir/config/config.yaml --server_ip 198.19.200.1 --push_buf_type singlebuf --debug_level info --inline_mode objectheader --message list-4 --serialization protobuf
sudo env LD_LIBRARY_PATH=/h/deeptir/cornflakes/dpdk-datapath/3rdparty/dpdk/install/lib/x86_64-linux-gnu /h/deeptir/cornflakes/target/release/ds_echo_dpdk --config_file /h/deeptir/config/config.yaml --server_ip 198.19.200.1 --our_ip 198.19.200.2 --push_buf_type singlebuf --mode client --debug_level info --rate 100000 --serialization capnproto --size 4096 --message list-4 --time 10 --num_threads 16
make clean; make CONFIG_MLX5=y DEBUG=n GDB=n TIMERS=n
cargo b --release --features profiler mlx5
sudo LD_LIBRARY_PATH=/h/deeptir/cornflakes/dpdk-datapath/3rdparty/dpdk/install/lib/x86_64-linux-gnu /h/deeptir/cornflakes/scatter-gather-bench/build/netperf -n 4 -w 0000:37:00.0,txq_inline_mpw=256,txqs_min_inline=0 --proc-type=auto -- --mode=CLIENT --server_ip=198.19.200.1 --client_ip=198.19.200.2 --server_mac=b8:83:03:79:af:40 --rate=200000 --segment_size=4096 --num_segments=1 --time=10  --random_seed=1638920199 --array_size=65536 --client_threads=4 --echo_mode
sudo nice -n -19 taskset -c 1 /h/deeptir/cornflakes/mlx5-netperf/build/mlx5-netperf  --mode=SERVER --pci_addr=0000:37:00.0 --server_mac=b8:83:03:79:af:40 --server_ip=198.19.200.1 --array_size=65536 --segment_size=2048 --num_segments=1
python3 cf-kv-bench.py -e loop -f ~/cornflakes/experiments/results/kv/ycsb_june20_22 -c ~/config/config.yaml -ec ~/cornflakes/cf-kv/ycsb.yaml -lt ~/ycsb-workloads/4K_250K_15M/workloadc/workloadc-1-batched.load -qt ~/ycsb-workloads/4K_250K_15M/workloadc/workloadc-1-batched.access
python3 mlx5-bench.py -e loop -f /h/deeptir/cornflakes/experiments/results/mlnx_sg_bench/june13_total_segment_cross_heatmap_no_batching -c ~/config/config.yaml -ec ~/cornflakes/experiments/yamls/mlx5-netperf.yaml --looping_variable total_segment_cross
cargo b --release --features profiler mlx5
