client_port: 12345
cornflakes_dir: /mydata/USER/cornflakes
dpdk:
  eal_init:
  - -c
  - '0xff'
  - -n
  - '8'
  - -a
  - '0000:41:00.1'
  - --proc-type=auto
  pci_addr: '0000:41:00.1'
  port: '1'
host_types:
  client:
  - client1
  server:
  - server
hosts:
  client1:
    addr: 128.XXX.XXX.XX
    config_file: /mydata/USER/config/cluster_config.yaml
    cornflakes_dir: /mydata/USER/cornflakes
    ip: 192.168.1.2
    mac: XX:XX:XX:XX:XX:XX
    tmp_folder: /mydata/USER/cornflakes_tmp
  server:
    addr: 128.XXX.XXX.XX
    config_file: /mydata/USER/config/cluster_config.yaml
    cornflakes_dir: /mydata/USER/cornflakes
    ip: 192.168.1.1
    mac: XX:XX:XX:XX:XX:XX
    tmp_folder: /mydata/USER/cornflakes_tmp
lwip:
  known_hosts:
    XX:XX:XX:XX:XX:XX: 192.168.1.1
    XX:XX:XX:XX:XX:XX: 192.168.1.2
max_clients: 1
mlx5:
  pci_addr: '0000:41:00.1'
port: 54321
user: USER
