[package]
name = "proto-codegen"
version = "0.1.0"
authors = ["deeptir <deeptir@cs.stanford.edu>"]
edition = "2018"

[dependencies]
structopt="0.2.16"
structopt-derive="0.2.16"
failure = "0.1.5"
tracing = "0.1.12"
tracing-subscriber = "0.1.6"
