[package]
name = "cornflakes-libos"
version = "0.1.0"
authors = ["deeptir <deeptir@cs.stanford.edu>"]
edition = "2018"

[build-dependencies]
bindgen = "0.55.1" 
cc = "1.0.63"

[dependencies]
color-eyre = "0.5"
tracing = "0.1.12"
tracing-subscriber = "0.1.6"
structopt="0.2.16"
structopt-derive="0.2.16"
yaml-rust = "0.4.3"

[features]
mlx5 = []

default = ["mlx5"]
