[package]
name = "cornflakes-libos"
version = "0.1.0"
authors = ["deeptir <deeptir@cs.stanford.edu>"]
edition = "2018"

[build-dependencies]
bindgen = "0.55.1" 
cc = "1.0.63"

[dependencies]
color-eyre = { version = "0.5", default-features = false }
tracing = "0.1.12"
tracing-subscriber = "0.1.6"
structopt="0.2.16"
structopt-derive="0.2.16"

[features]
mlx5 = []

default = ["mlx5"]
